//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package trpc_test_testproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	SleepTimeMs          int32    `protobuf:"varint,2,opt,name=sleep_time_ms,json=sleepTimeMs,proto3" json:"sleep_time_ms,omitempty"`
	ErrorCodeReturned    uint32   `protobuf:"varint,3,opt,name=error_code_returned,json=errorCodeReturned,proto3" json:"error_code_returned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PingRequest) GetSleepTimeMs() int32 {
	if m != nil {
		return m.SleepTimeMs
	}
	return 0
}

func (m *PingRequest) GetErrorCodeReturned() uint32 {
	if m != nil {
		return m.ErrorCodeReturned
	}
	return 0
}

type PingResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Counter              int32    `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PingResponse) GetCounter() int32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "trpc.test.testproto.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "trpc.test.testproto.PingResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x59, 0xe5, 0xfc, 0x33, 0xf1, 0x0a, 0xf7, 0x2c, 0x82, 0x55, 0x4c, 0x95, 0x6a, 0x11,
	0xed, 0x6d, 0x6c, 0x15, 0x74, 0xbd, 0x3e, 0x6a, 0xf2, 0x90, 0x85, 0x4b, 0x36, 0xce, 0x4c, 0xce,
	0xaf, 0x2f, 0xb7, 0x89, 0x60, 0xa1, 0xd7, 0x0c, 0xbc, 0xdf, 0x1b, 0xe6, 0xcd, 0x23, 0x52, 0x88,
	0xba, 0x81, 0xa3, 0x46, 0xbb, 0x52, 0x1e, 0x1a, 0x97, 0xc0, 0x6e, 0x24, 0x58, 0x7e, 0x51, 0xf6,
	0x14, 0xfa, 0x0f, 0x8f, 0xcf, 0x11, 0xa2, 0xf6, 0x82, 0x16, 0xdb, 0xb7, 0xcd, 0x88, 0xdc, 0x14,
	0xa6, 0x3a, 0xf5, 0x93, 0xb0, 0x25, 0x2d, 0x65, 0x03, 0x0c, 0xb5, 0x86, 0x0e, 0x75, 0x27, 0xf9,
	0x41, 0x61, 0xaa, 0x85, 0xcf, 0x12, 0x5c, 0x87, 0x0e, 0x8f, 0x62, 0x1d, 0xad, 0xc0, 0x1c, 0xb9,
	0x6e, 0x62, 0x8b, 0x9a, 0xa1, 0x23, 0xf7, 0x68, 0xf3, 0xc3, 0xc2, 0x54, 0x4b, 0x7f, 0x9e, 0xac,
	0xfb, 0xd8, 0xc2, 0xcf, 0x46, 0x79, 0x47, 0x67, 0x53, 0xb0, 0x0c, 0xb1, 0x17, 0xfc, 0x93, 0x9c,
	0xd3, 0x71, 0x13, 0xc7, 0x5e, 0xc1, 0x73, 0xe6, 0x8f, 0xbc, 0x79, 0xa5, 0x6c, 0x0d, 0xd1, 0x17,
	0xf0, 0x36, 0x34, 0xb0, 0xcf, 0x74, 0xb2, 0x3b, 0xf7, 0x10, 0x44, 0x6d, 0xe1, 0xfe, 0x68, 0xea,
	0x7e, 0xd5, 0xbc, 0xbc, 0xda, 0xb3, 0x31, 0xfd, 0x73, 0x6d, 0xde, 0x8f, 0x12, 0xbd, 0xfd, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0x36, 0x89, 0x5e, 0x44, 0x01, 0x00, 0x00,
}
